### PR TITLE
Added callback for speech finish and new pause and resume methods

### PR DESCRIPTION
**Pull request by stefalda**
Hi,
 I've implemented both for iOS and for Android the delegation pattern to be able to be notified when the speech has finished.
I've also added two method to pause and resume speech, and updated the documentation.

Give it a try and if you see no issue you can merge the changes.

Stefano

### CODE REVIEW

**Comment by bradmartin** [comment]
@stefalda - I'll refactor this into the typescript files and get it published asap. Nice work 👍

**Comment by bradmartin** [comment]
I did a lot of refactoring to TS, used your code for the methods you added and the finished event. Android is working great, could you review the pause/resume for iOS and then possibly rebase and PR the fix. I don't think it's working, but didn't test thoroughly. Thanks!

**Comment by stefalda** [comment]
Hi @bradmartin, sorry for the delay... I'll try to rebase asap...

**Comment by bradmartin** [comment]
I think I left off and only the iOS pieces needed a little touching up.
Android seemed to work great. It's likely a variable out of place or
something I overlooked. I rewrote it pretty quick so might have just missed
something :) thanks. If you don't have time I'll circle back to it
eventually. No issues filled on it yet which is good.

**Pull request closed without merging**
